### PR TITLE
Feature/60 add new dropdwon UI

### PR DESCRIPTION
**Pull request by cmcWebCode40**
## Task

- [x] Updated Dropdown UI from figma https://www.figma.com/file/KUUXMIaE7OyRwEdW173wr5/Account-Explorer-App?node-id=387%3A5620

## Demo

https://www.loom.com/share/338c6864507f40359aeedc73bc8fd401
(I will update with the correct icons when I upload them to our cloud assets )

### CODE REVIEW

**Comment by nick-verida** [comment]
We can't have "Manage Tokens" or "Verida Token" in this menu until those features are ready.

However moving the icons etc is fine to do now

**Review by nick-verida — CHANGES_REQUESTED** [review]
See comment

**Comment by cmcWebCode40** [comment]
@nick-verida, 

There's is an optional prop `navItem`(an array)  that can be passed to the `vda-account` to display a list of items, this will be useful if developers configure the components to support other links in their app. I also added documentation to this her [README](https://github.com/verida/verida-vue-components/blob/feature/60-add-new-dropdwon-ui/components/account/README.md)

But for now, I have removed links to features that are not complete.

**Review by nick-verida — APPROVED** [review]
looks good, merging

**Pull request merged**
