### PR TITLE
remove TextEncoder fix. closes #41

### LINKED ISSUE #41: Fix for TextEncoder in test redefines global TextEncoder
These lines in `tests/unit/account/vda-account.spec.ts`

```
declare var global: any

if (typeof TextEncoder === 'undefined') global.TextEncoder = require('text-encoding-shim').TextEncoder
if (typeof TextDecoder === 'undefined') global.TextDecoder = require('text-encoding-shim').TextDecoder
```

somehow get transpiled and included in the core code for the module as:

```
/* eslint-disable @typescript-eslint/no-explicit-any */
global.TextEncoder = require("util").TextEncoder;
global.TextDecoder = require("util").TextDecoder;
```

This breaks lots of things. See https://github.com/verida/demo-credential-issuer/issues/48

### PR DESCRIPTION
**Pull request by nick-verida**
Fix for #41

### CODE REVIEW

**Comment by tahpot** [comment]
@nick-verida If this is only used in the unit test, then `text-encoding-shim` should be a `devDependency`?

**Comment by nick-verida** [comment]
@tahpot yes, good point. 

The big question is how some code I wrote in the test ended up generating code that imported a different package in the module (non-test) code. I don't understand that _at all_.

Either way, it isn't needed now so I've removed the dependency completely.

**Comment by tahpot** [comment]
>The big question is how some code I wrote in the test ended up generating code that imported a different package in the module (non-test) code. I don't understand that at all.

Totally agreed. I was thinking the same.

**Review by cmcWebCode40 — APPROVED** [review]
@nick-verida , the SSO login still works correctly , 

but I have been getting a weird error trying to link the `vue-account` component locally, I can only use it when the package is published so I can test in the `credential-issuer-demo`

**Review by tahpot — APPROVED** [review]
Looks good

**Pull request merged**
